### ISSUE TITLE
add footer to bottom of page

### ISSUE THREAD

**Issue by ggongg** [MLH-Fellowship/prep-project-22.AUG.PREP.2#29] opened 2022-08-11 17:45 UTC
some examples of foot content can be the mlh wording, and mention cohort. and potentially mlh social medias

**Comment by ahmedsaed** [comment] 2022-08-12 15:06
I think this issue is a duplicate of #23. if so, then close this one and maybe add your suggestions to the other issue

**Closed as completed** 2022-08-13 12:56 UTC
Labels: enhancement
